Repository team-wanna/check-mate, pull requests merged in 2021-12, with the labels that each got.

#42 B20 - 기본 이미지로 변경하는 API 추가
  backend/src/projects/projects.controller.ts
  backend/src/projects/projects.service.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
Labels: 🧵 백엔드, ⚙ 기능

#43 F10 - 프로젝트 카드 컴포넌트
  frontend/src/api/modules/auth.ts
  frontend/src/components/UI/atoms/LoginButton.vue
  frontend/src/components/UI/atoms/ProjectCard.vue
  frontend/src/components/UI/atoms/Toast.vue
  frontend/src/components/UI/organisms/NavigationBar.vue
  frontend/src/components/pages/Home.vue
  frontend/src/components/pages/Profile.vue
  frontend/src/components/pages/SignInModal.vue
  frontend/src/components/templates/BaseModal.vue
  frontend/src/style/common.scss
  frontend/src/style/main.scss
Labels: 🖼 프론트엔드, ⚙ 기능

#45 B21 - API 서비스 로직 리팩토링
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/jwt/jwt.strategy.ts
  backend/src/aws/aws.service.ts
  backend/src/main.ts
  backend/src/projects/projects.controller.ts
  backend/src/projects/projects.service.ts
  backend/src/skills/dto/skill.dto.ts
  backend/src/skills/skills.controller.ts
  backend/src/users/dto/another-user.dto.ts
  backend/src/users/dto/user.dto.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
Labels: 🧵 백엔드

#47 B22 - 스킬 value 컬럼 추가
  backend/src/entities/skills.entity.ts
  backend/src/projects/projects.controller.ts
  backend/src/projects/projects.service.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
Labels: 🧵 백엔드, ⚙ 기능

#49 B23 - 회원탈퇴시 프로필 이미지 S3 객체 삭제
  backend/src/projects/projects.service.ts
  backend/src/users/users.service.ts
Labels: 🧵 백엔드, ⚙ 기능

#52 F08 - 기술스택 아이템 컴포넌트
  backend/package-lock.json
  frontend/src/api/modules/skill.ts
  frontend/src/api/modules/user.ts
  frontend/src/common/Utils.ts
  frontend/src/components/UI/atoms/SkillItem.vue
  frontend/src/components/UI/atoms/Toast.vue
  frontend/src/components/pages/Profile.vue
  frontend/src/style/config.scss
Labels: 🖼 프론트엔드, ⚙ 기능

#54 B24 - 프로젝트 리스트 필터링 & 페이지네이션 구현
  backend/src/entities/projects.entity.ts
  backend/src/projects/projects.controller.ts
  backend/src/projects/projects.service.ts
Labels: 🧵 백엔드, ⚙ 기능

#55 F12 - API 모듈 코드 리팩토링
  frontend/src/api/modules/auth.ts
  frontend/src/api/modules/auth/index.ts
  frontend/src/api/modules/auth/types.ts
  frontend/src/api/modules/skill.ts
  frontend/src/api/modules/skills/index.ts
  frontend/src/api/modules/skills/types.ts
  frontend/src/api/modules/user.ts
  frontend/src/api/modules/users/index.ts
  frontend/src/api/modules/users/types.ts
  frontend/src/components/UI/atoms/SkillItem.vue
  frontend/src/components/pages/Home.vue
  frontend/src/components/pages/Login.vue
  frontend/src/components/pages/Profile.vue
Labels: 🖼 프론트엔드
