Repository team-wanna/check-mate, pull requests merged in 2021-10, with the labels that each got.

#4 B09 - 최초 로그인 시 유저 name 저장하지 않도록 수정
  backend/src/auth/auth.service.ts
  backend/src/auth/passport/facebook.strategy.ts
  backend/src/auth/passport/github.strategy.ts
  backend/src/auth/passport/google.strategy.ts
  backend/src/users/users.entity.ts
Labels: 🧵 백엔드, ⚙ 기능

#10 B11 - API 문서화
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/auth.dto.ts
  backend/src/common/decorators/api-response-dto.decorator.ts
  backend/src/projects/dto/create-project.dto.ts
  backend/src/projects/dto/update-project.dto.ts
  backend/src/projects/projects.controller.ts
  backend/src/projects/projects.entity.ts
  backend/src/projects/projects.service.ts
  backend/src/users/dto/update-user.dto.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.entity.ts
  backend/src/users/users.service.ts
  frontend/package-lock.json
Labels: 🧵 백엔드

#25 B15 - 유저 서브 아이디 암호화
  backend/src/auth/auth.service.ts
Labels: 🧵 백엔드, ⚙ 기능

#26 F05 - 프로필 팝업 연계 및 로그아웃 구현
  frontend/public/index.html
  frontend/src/components/UI/atoms/LoginButton.vue
  frontend/src/components/UI/organisms/NavigationBar.vue
  frontend/src/style/config.scss
Labels: 🖼 프론트엔드, ⚙ 기능
