Repository team-wanna/check-mate, pull requests merged in 2022-01, with the labels that each got.

#60 B25 - 즐겨찾기 등록/해제 API 구현
  backend/src/entities/projects.entity.ts
  backend/src/entities/users.entity.ts
  backend/src/projects/dto/stared-project.dto.ts
  backend/src/projects/projects.controller.ts
  backend/src/projects/projects.service.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.ts
Labels: 🧵 백엔드, ⚙ 기능

#62 F12 - 새로고침 시 유저 데이터 유지
  frontend/src/api/modules/skills/index.ts
  frontend/src/api/modules/skills/types.ts
  frontend/src/api/modules/users/index.ts
  frontend/src/api/modules/users/types.ts
  frontend/src/components/UI/atoms/LoginButton.vue
  frontend/src/components/UI/atoms/SkillItem.vue
  frontend/src/components/UI/atoms/SocialLoginButton.vue
  frontend/src/components/pages/Home.vue
  frontend/src/components/pages/Login.vue
  frontend/src/components/pages/Profile.vue
  frontend/src/store/modules/user.ts
Labels: 🖼 프론트엔드, ⚙ 기능

#67 F16 - Message Box 컴포넌트
  frontend/src/components/UI/atoms/MessageBox.vue
  frontend/src/components/pages/SignInModal.vue
  frontend/src/style/config.scss
Labels: 🐛 버그, ⚙ 기능

#68 F15 - 회원가입 후 로그인이 안되는 현상 수정
  frontend/src/api/modules/users/index.ts
  frontend/src/api/modules/users/types.ts
  frontend/src/components/UI/atoms/LoginButton.vue
  frontend/src/components/pages/Home.vue
  frontend/src/components/pages/Profile.vue
  frontend/src/components/pages/SignUpModal.vue
  frontend/src/router/index.ts
  frontend/src/store/modules/user.ts
Labels: 🐛 버그, 🖼 프론트엔드

#69 F14 - 로그인, 로그아웃 시 토스트 메시지
  frontend/src/components/UI/atoms/LoginButton.vue
  frontend/src/components/pages/Home.vue
Labels: 🖼 프론트엔드, ⚙ 기능

#74 B29 - 기본 이미지 설정 기능 수정
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
Labels: 🧵 백엔드, ⚙ 기능

#77 B27 - 알람 기능 개발
  backend/src/alarms/alarms.controller.spec.ts
  backend/src/alarms/alarms.controller.ts
  backend/src/alarms/alarms.module.ts
  backend/src/alarms/alarms.service.spec.ts
  backend/src/alarms/alarms.service.ts
  backend/src/alarms/dto/create-alarm.dto.ts
  backend/src/app.module.ts
  backend/src/common/types/AlarmType.ts
  backend/src/entities/alarm.entity.ts
Labels: 🧵 백엔드, ⚙ 기능

#79 B30 - 프로젝트 가입 요청/응답 알람 기능 적용하여 구현
  backend/src/alarms/alarms.controller.ts
  backend/src/alarms/alarms.service.ts
  backend/src/projects/projects.controller.ts
  backend/src/projects/projects.service.ts
Labels: 🧵 백엔드, ⚙ 기능

#81 F18 - 스킬아이템 컴포넌트 디자인 수정
  frontend/src/common/Utils.ts
  frontend/src/components/UI/atoms/MessageBox.vue
  frontend/src/components/UI/atoms/SkillItem.vue
  frontend/src/components/UI/atoms/Toast.vue
  frontend/src/components/UI/organisms/NavigationBar.vue
  frontend/src/components/templates/BaseModal.vue
Labels: 🐛 버그, 🖼 프론트엔드, ⚙ 기능
